config/routes.rb
Rails.application.routes.draw do
    root :to => 'mandrill_notifications#index'
    namespace :webhooks do
        post 'mandrill/create', to: 'mandrill#create', as: 'create_mandrill_webhook'
    end
    resources :mandrill_notifications, only: [:index, :show]
end

app/models/mandrill_notification.rb
class MandrillNotification < ActiveRecord::Base
    def self.filtered(params)
        return self if params.nil?
        result = self
        unless params[:event].blank?
            result = result.where(event: params[:event])
        end
        unless params[:email_type].blank?
            result = result.where(email_type: params[:email_type])
        end
        result
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    include StatsHelper
end

app/controllers/concerns/stats_helper.rb
module StatsHelper
    def calculate_click_rate(email_type)
        total_sent = MandrillNotification.where(email_type: email_type, event: 'send').count.to_f
        total_clicked = MandrillNotification.where(email_type: email_type, event: 'click').count.to_f
        click_rate = (total_clicked / total_sent) * 100 unless total_sent.zero?
        click_rate
    end

    def calculate_open_rate(email_type)
        total_sent = MandrillNotification.where(email_type: email_type, event: 'send').count.to_f
        total_opened = MandrillNotification.where(email_type: email_type, event: 'open').count.to_f
        open_rate = (total_opened / total_sent.to_f) * 100 unless total_sent.zero?
        open_rate
    end
end

app/controllers/mandrill_notifications_controller.rb
class MandrillNotificationsController < ApplicationController
    def index
        @mandrill_notifications        = MandrillNotification.filtered(params).order('id desc').page(params[:page])
        @email_type                    = params[:email_type].present? ? params[:email_type] : nil
        @click_rate                    = calculate_click_rate(@email_type)
        @open_rate                     = calculate_open_rate(@email_type)
    end

    def show
        @mandrill_notification = MandrillNotification.find(params[:id])
    end
end

app/controllers/webhooks/mandrill_controller.rb
module Webhooks
    class MandrillController < ApplicationController
        skip_before_action :verify_authenticity_token, only: [:create]

        def create
            payload = JSON.parse(request.body.read) if request.body
            if %w(send click open).include? payload['Event']
                email_type = payload['EmailType'].downcase if payload['EmailType'].present?
                MandrillNotification.create(event: payload['Event'],
                                            email_address: payload['Address'],
                                            email_type: email_type,
                                            raw_payload: payload)
            end
            render status: 200, nothing: true
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_time(t, separator = false)
        return I18n.l(t, format: '%d.%m.%Y - %H:%M:%S') if t && separator
        return I18n.l(t, format: '%d.%m.%Y %H:%M:%S') if t
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mandrill_notifications/_header.html.erb
<tr>
    <th>Time</th>
    <th>Event</th>
    <th>Email Address</th>
    <th>Email Type</th>
</tr>

app/views/mandrill_notifications/_mandrill_notification.html.erb
<tr>
    <td><%= link_to format_time(mandrill_notification.created_at), mandrill_notification_path(mandrill_notification) %></td>
    <td><%= mandrill_notification.event %></td>
    <td><%= mandrill_notification.email_address %></td>
    <td><%= mandrill_notification.email_type %></td>
</tr>

app/views/mandrill_notifications/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Mandrill Notifications</h3>
    </div>
    <div class="row">
        <div>
            <%= form_tag mandrill_notifications_path, method: :get do %>
                <div>
                    <div>
                        <label>Event</label>
                        <%= select_tag :event, options_for_select(MandrillNotification.all.map(&:event).uniq, params[:event]), include_blank: true %>
                    </div>
                    <div>
                        <label>Email Type</label>
                        <%= select_tag :email_type, options_for_select(MandrillNotification.all.map(&:email_type).uniq, params[:email_type]), include_blank: true %>
                    </div>
                </div>
                <div>
                    <div>
                        <button type="submit">filter</button>
                    </div>
                </div>
            <% end %>
            <h4 class="panel-title"> Total: <%= @mandrill_notifications.count %></h4>
        </div>
    </div>
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-condensed table-bordered table-striped table-hover">
                <% if @email_type %>
                    <h4>Email Type: <%= @email_type %></h4>
                    <% if @click_rate %>
                        <dl>
                            <dt style="float: left;">Click Rate: </dt><dd><%= number_to_percentage(@click_rate, precision: 0) %></dd>
                            <dt style="float: left;">Open Rate: </dt><dd><%= number_to_percentage(@open_rate, precision: 0) %></dd>
                        </dl>
                    <% else %>
                        No stats to show. No sent notifications have been received for email type: <%= @email_type %>. Try sending an  <%= @email_type %> email.
                    <% end %>
                <% end %>
                <hr>
                <% if @mandrill_notifications.count.positive? %>
                        <thead>
                            <%= render 'mandrill_notifications/header' %>
                        </thead>
                        <tbody>
                            <%= render partial: 'mandrill_notifications/mandrill_notification', collection: @mandrill_notifications %>
                        </tbody>
                    <%= will_paginate @mandrill_notifications, renderer: BootstrapPagination::Rails %>
                <% end %>
           </table>
        </div>
    </div>
</div>

app/views/mandrill_notifications/show.html.erb
<div>
    <div>
        <h3>Mandrill Notification <%= @mandrill_notification.id %></h3>
    </div>
    <div>
        <dl>
            <dt>Event: </dt><dd"><%= @mandrill_notification.event %></dd>
            <dt>Email Address: </dt><dd"><%= @mandrill_notification.email_address %></dd>
            <dt>Email Type: </dt><dd"><%= @mandrill_notification.email_type %></dd>
            <dt>Created At: </dt><dd"><%= format_time @mandrill_notification.created_at %></dd>
        </dl>
    </div>
</div>